CREATE  TABLE "public".annotation_detail ( 
	annotermid           integer GENERATED BY DEFAULT AS IDENTITY  NOT NULL ,
	annoclassid          integer  NOT NULL ,
	annoterm             varchar(400)  NOT NULL ,
	CONSTRAINT annotation_detail_pkey PRIMARY KEY ( annotermid ),
	CONSTRAINT annotat_annoclassid_07b9abba_fk_dataenric FOREIGN KEY ( annoclassid ) REFERENCES "public".annotation_class( annoclassid )  
 );

CREATE INDEX annotation_detail_annoclassid_07b9abba ON "public".annotation_detail ( annoclassid ASC );


ALTER TABLE chemical_detail  
	ADD COLUMN casrnuid             integer GENERATED BY DEFAULT AS IDENTITY  NOT NULL ,
	ADD COLUMN testsubstance_chemname varchar(500)  NOT NULL DEFAULT 'default',
	ADD COLUMN molecular_formular   varchar(50)   ,
	ADD COLUMN iupac_name           varchar(1000)   ,
	ADD COLUMN inchis               varchar(1000)   ,
	ADD COLUMN inchikey             varchar(30)  
;

CREATE  TABLE "public".chemical_detail ( 
	casrnuid             integer GENERATED BY DEFAULT AS IDENTITY  NOT NULL ,
	casrn                varchar(15)  NOT NULL ,
	testsubstance_chemname varchar(500)  NOT NULL ,
	molecular_formular   varchar(50)   ,
	iupac_name           varchar(1000)   ,
	inchis               varchar(1000)   ,
	inchikey             varchar(30)   ,
	smiles               varchar(600)   ,
	CONSTRAINT chemical_detail_pkey PRIMARY KEY ( casrnuid )
 );
