CREATE  TABLE "public".annotation_class ( 
	annoclassid          integer GENERATED BY DEFAULT AS IDENTITY  NOT NULL ,
	annoclassname        varchar(50)  NOT NULL ,
	firsttermid          integer  NOT NULL ,
	lasttermid           integer  NOT NULL ,
	numberoftermids      integer  NOT NULL ,
	baseurl              varchar(255)  NOT NULL ,
	CONSTRAINT annotation_class_pkey PRIMARY KEY ( annoclassid )
 );

CREATE  TABLE "public".annotation_detail ( 
	annotermid           integer GENERATED BY DEFAULT AS IDENTITY  NOT NULL ,
	annoterm             varchar(400)  NOT NULL ,
	annoclassid          integer  NOT NULL ,
	CONSTRAINT annotation_detail_pkey PRIMARY KEY ( annotermid ),
	CONSTRAINT annotat_annoclassid_07b9abba_fk_dataenric FOREIGN KEY ( annoclassid ) REFERENCES "public".annotation_class( annoclassid )  
 );

CREATE INDEX annotation_detail_annoclassid_07b9abba ON "public".annotation_detail ( annoclassid ASC );

CREATE  TABLE "public".annoterm_pairwise ( 
	pairwiseid           integer GENERATED BY DEFAULT AS IDENTITY  NOT NULL ,
	term1uid             integer  NOT NULL ,
	term2uid             integer  NOT NULL ,
	term1size            integer  NOT NULL ,
	term2size            integer  NOT NULL ,
	common               integer  NOT NULL ,
	"union"              integer  NOT NULL ,
	jaccardindex         float8  NOT NULL ,
	pvalue               float8  NOT NULL ,
	qvalue               float8  NOT NULL ,
	CONSTRAINT annoterm_pairwise_pkey PRIMARY KEY ( pairwiseid )
 );

ALTER TABLE chemical_detail  
	ADD COLUMN casrnuid             integer GENERATED BY DEFAULT AS IDENTITY  NOT NULL ,
	ADD COLUMN testsubstance_chemname varchar(500)  NOT NULL DEFAULT 'default',
	ADD COLUMN molecular_formular   varchar(50)   ,
	ADD COLUMN iupac_name           varchar(1000)   ,
	ADD COLUMN inchis               varchar(1000)   ,
	ADD COLUMN inchikey             varchar(30)  
;

CREATE  TABLE "public".chemicals_tox21 ( 
	casrnuid             integer GENERATED BY DEFAULT AS IDENTITY  NOT NULL ,
	casrn                varchar(15)  NOT NULL ,
	testsubstance_chemname varchar(500)  NOT NULL ,
	molecular_formular   varchar(50)  NOT NULL ,
	iupac_name           varchar(1000)  NOT NULL ,
	inchis               varchar(1000)  NOT NULL ,
	inchikey             varchar(30)  NOT NULL ,
	smiles               varchar(600)  NOT NULL ,
	CONSTRAINT chemicals_tox21_pkey PRIMARY KEY ( casrnuid )
 );


CREATE  TABLE "public".term2casrn_mapping ( 
	term2casrnmappinguid integer GENERATED BY DEFAULT AS IDENTITY  NOT NULL ,
	annotermid           integer  NOT NULL ,
	annoclassid          integer  NOT NULL ,
	casrnuid_id          integer  NOT NULL ,
	CONSTRAINT term2casrn_mapping_pkey PRIMARY KEY ( term2casrnmappinguid ),
	CONSTRAINT term2ca_casrnuid_id_a80baf5a_fk FOREIGN KEY ( casrnuid_id ) REFERENCES "public".chemical_detail( casrnuid )  
 );

CREATE INDEX term2casrn_mapping_casrnuid_id_a80baf5a ON "public".term2casrn_mapping ( casrnuid_id ASC );


CREATE OR REPLACE FUNCTION public.dice_sml(sfp, sfp)
 RETURNS double precision
 LANGUAGE c
 IMMUTABLE STRICT COST 10
AS '$libdir/rdkit', $function$sfp_dice_sml$function$
;

CREATE OR REPLACE FUNCTION public.dice_sml_op(sfp, sfp)
 RETURNS boolean
 LANGUAGE c
 IMMUTABLE STRICT COST 10
AS '$libdir/rdkit', $function$sfp_dice_sml_op$function$
;

