---
grails:
    servlet:
        version: 3.0
    profile: web
    codegen:
        defaultPackage: tox21
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false

---
micronaut:
    codec:
        json:
            additionalTypes:
                - text/javascript
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html: 
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            rss: application/rss+xml
            text: text/plain
            hal: 
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    hibernate:
        cache:
            queries: false
            use_second_level_cache: false
            use_query_cache: false
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
---
dataSources:
    psql:
        pooled: true
        driverClassName: org.postgresql.Driver
        dialect: org.hibernate.dialect.PostgreSQLDialect
        url: jdbc:postgresql://127.0.0.1:5432/tox21enricher
        username: username
        password: "password"
environments:
    development:
        server:
            servlet:
                context-path: '/tox21enricher'
        dataSources:
            psql:
                dbCreate: validate
                url: jdbc:postgresql://127.0.0.1:5432/tox21enricher
    test:
        server:
            servlet:
                context-path: '/tox21enricher'
        dataSources:
            psql:
                dbCreate: validate
                url: jdbc:postgresql://127.0.0.1:5432/tox21enricher
    production:
        server:
            servlet:
                context-path: '/tox21enricher'
        dataSources:
            psql:
                dbCreate: validate
                url: jdbc:postgresql://127.0.0.1:5432/tox21enricher

